# Generated by Django 3.2.3 on 2021-08-24 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.datetime.now)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_fees_fee', to='fees.fee')),
            ],
        ),
    ]
