# Generated by Django 3.2.3 on 2021-08-24 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player_fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerfees',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_fees_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerfees',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_fees_team', to='teams.team'),
        ),
    ]
