# Generated by Django 3.2.3 on 2021-08-19 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerfees',
            name='time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
