# Generated by Django 3.2.3 on 2021-08-15 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('currency', models.CharField(max_length=128, verbose_name='Currency')),
                ('players', models.ManyToManyField(blank=True, related_name='player_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
