# Generated by Django 3.2.3 on 2021-08-24 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='player_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
