# Generated by Django 3.2.3 on 2021-08-19 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
