# Generated by Django 3.2.3 on 2021-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='currency',
            field=models.CharField(default='CZK', max_length=128, verbose_name='Currency'),
            preserve_default=False,
        ),
    ]
