# Generated by Django 3.2.3 on 2021-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20211004_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='account_prefix',
            field=models.CharField(blank=True, max_length=128, verbose_name='Account prefix'),
        ),
    ]
